config/routes.rb
AAAWebsite::Application.routes.draw do
  resources :comments

  devise_for :users
  resources :events

  root :to => 'aaa_core#index'
  get '/shop', :to => 'aaa_core#shop'
  get '/discussion', :to => 'aaa_core#discussion'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :event_id, :details, :author
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :title, :date, :description 
  has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController
  def index
    @title = "Home"
  end

  def shop
    @title = "Shop"
  end

  def discussion
    @title = "Discussion Forum"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(event_id: params[:event_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:event_id, :details, :author)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
    
    def authenticate_user
    end
end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Ashtead Allotments Association"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/index.html.erb
<article>
  <section id="main">
    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam in quam odio. Sed nec volutpat mi, vitae gravida lacus. Vestibulum nec massa rhoncus, luctus leo aliquet, mattis ligula. In ornare gravida nulla a rutrum. Cras rhoncus, nulla ut vehicula vulputate, ligula enim elementum orci, nec ornare velit risus non risus. Vestibulum orci ipsum, ullamcorper sit amet dui id, tincidunt feugiat ipsum. Ut sit amet lorem enim. Integer quis lacus vitae nisl feugiat tincidunt. Proin feugiat, nibh sit amet lacinia imperdiet, quam sem malesuada quam, a ullamcorper nulla purus sed diam. Nulla at gravida nunc, sed scelerisque diam. Cras nec felis et risus commodo molestie a aliquam ante. Nulla vestibulum urna vel congue consectetur. Praesent congue volutpat risus et ullamcorper.
    </p>
    
    <p>
    Maecenas sit amet nisi diam. Duis hendrerit elit est, nec iaculis justo convallis eget. Aliquam leo dui, ornare vitae metus non, tincidunt convallis tortor. In semper facilisis nulla, at ornare leo suscipit eget. In nec accumsan eros, sit amet euismod leo. Vestibulum vehicula, nibh non porttitor bibendum, sem tortor viverra odio, ac commodo lorem eros nec neque. Quisque non fringilla ante, nec egestas quam. Nullam nibh nulla, vehicula a ultrices vel, congue eget neque. Maecenas consectetur mollis enim ultrices auctor. Vivamus vitae lacus et magna cursus bibendum. Quisque sed nunc a mauris ullamcorper fermentum ut in mi. Proin posuere vulputate nulla sed accumsan. Sed pulvinar enim massa, a ullamcorper elit mattis non. Aenean ut est quis arcu tempus mollis.
    </p>
  </section>
  <section id="sidebar">
    <p>
    Vestibulum sollicitudin sed leo eget euismod. Cras posuere hendrerit massa nec placerat. Aliquam interdum mattis enim quis auctor. Ut interdum eget libero a ornare. Vestibulum pellentesque turpis sed consectetur pulvinar. Maecenas porttitor, sapien sit amet ultrices lacinia, nulla tellus imperdiet sem, sit amet tincidunt massa tortor in lectus. Nunc lorem nulla, sagittis id enim nec, iaculis varius diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec porta fringilla suscipit. Phasellus semper urna sollicitudin elit euismod tristique.
    </p>
  </section>
</article>

app/views/aaa_core/shop.html.erb
<h1>AaaCore#shop</h1>
<p>Find me in app/views/aaa_core/shop.html.erb</p>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :event_id %>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Details</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.event_id %></td>
        <td><%= comment.details %></td>
        <td><%= comment.author %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @comment.event_id %>
</p>

<p>
  <strong>Details:</strong>
  <%= @comment.details %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<article id="events">

  <% @events.each do |event| %>
    <section>
      <h1><%= event.title %></h1>
      <h2>Date of event: <%= event.date %></h2>
      <p>
        <%= event.description %>
      </p>
      <% if user_signed_in? %>
        <p>
          <%= link_to 'Show', event %>
          <%= link_to 'Edit', edit_event_path(event) %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      <% end %>
    </section>
  <% end %>
  
  <% if user_signed_in? %>
    <section>
      <%= link_to 'New Event', new_event_path %>
    </section>
  <% end %>
  
</article>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'New Comment', new_comment_path(event_id: @event) %> |
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer>
  &copy; <%= Time.now.year %> Ashtead Allotment's Association
</footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">
  <nav id="utility">
    <% if user_signed_in? %>
		Signed in as <%= current_user.email%>
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
	<% end %>
  </nav>
  <h1>Ashtead Allotments Association</h1>
  <h2>Healthy Eating and Exercise preserve Life's Balance</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav id="main_nav" role="navigation">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Events", events_path %></li>
    <li><%= link_to "Discussion", discussion_path %></li>
    <li><%= link_to "Shop", shop_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<%= render 'layouts/header' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= render 'layouts/navigation' %>

<%= yield %>

<%= render 'layouts/footer' %>
</div>
</body>
</html>